### ISSUE TITLE
background page info

### ISSUE THREAD

**Issue by sebastien-violante** [WildCodeSchool/purple-php-2109-project2-quizzy#18]
Sur version mobile (Chrome) le fond d'écran bleu ne couvre pas la totalité du texte 
Sur version desktop, le texte s'affiche en colonnes (Chrome et Firefox)

**Comment by Benjamin-51** [comment]
I'm sorry, what page are you referencing?

**Comment by soufcod3** [comment]
On the /legalnotices

**Comment by MorganeL-pro** [comment]
Thanks for your message. 
We solved this problem.
