### ISSUE TITLE
delete an answer

### ISSUE THREAD

**Issue by sebastien-violante** [WildCodeSchool/purple-php-2109-project2-quizzy#23]
Hi once again,

When I want to delete a question, it seems that I can't choose the one I want to delete. And it's always the last one. If I've made an error when writing the first one, the only solution is to delete the question.

**Comment by MorganeL-pro** [comment]
It will be for another version because for now, there is no user panel.
Only the admin can manage the questions added by users.

**Comment by iStyyx** [comment]
you can just edit the input directly 🤷‍♂️
